dev(PEP 425) [ci skip]

diff --git a/.github/workflows/create-release-draft.yml b/.github/workflows/create-release-draft.yml
--- a/.github/workflows/create-release-draft.yml
+++ b/.github/workflows/create-release-draft.yml
@@ -76,75 +76,75 @@ jobs:
           path: wheelhouse/*.whl
           if-no-files-found: error
 
-  wheels_linux_cpython:
-    strategy:
-      fail-fast: true
-      matrix:
-        cibw_buildlinux: [ manylinux, musllinux ]
-        cibw_arch: [ "aarch64", "i686", "x86_64" ]
-    name: Wheels • ${{ matrix.cibw_buildlinux }} • ${{ matrix.cibw_arch }} • CPython
-    runs-on: ubuntu-20.04
-    env:
-      BUILD_DIR_PREFIX: "/tmp/pillow_heif"
-      KEY_HEAD: ${{ matrix.cibw_arch }}-${{ matrix.cibw_buildlinux }}
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up QEMU
-        if: matrix.cibw_arch == 'aarch64'
-        uses: docker/setup-qemu-action@v1
-        with:
-          platforms: arm64
-
-      - name: Install cibuildwheel & twine
-        run: python3 -m pip install cibuildwheel twine
-
-      - name: manylinux preparations
-        if: matrix.cibw_buildlinux == 'manylinux'
-        run: echo INSTALL_OS_PACKAGES="yum makecache && yum install -y $OS_PACKAGES" >> $GITHUB_ENV
-        env:
-          OS_PACKAGES: "git-all libjpeg-turbo-devel lcms2-devel"
-
-      - name: musllinux preparations
-        if: matrix.cibw_buildlinux == 'musllinux'
-        run: echo INSTALL_OS_PACKAGES="apk update && apk --no-cache add $OS_PACKAGES" >> $GITHUB_ENV
-        env:
-          OS_PACKAGES: "sudo py3-pip python3-dev fribidi-dev harfbuzz-dev jpeg-dev lcms2-dev openjpeg-dev"
-
-      - name: Only minimal testing on aarch64
-        if: matrix.cibw_arch == 'aarch64'
-        run: echo CIBW_TEST_EXTRAS="tests-min" >> $GITHUB_ENV
-
-      - uses: actions/cache@v3
-        with:
-          path: ${{ env.BUILD_DIR_PREFIX }}/build-tools
-          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.py') }}
-
-      - uses: actions/cache@v3
-        with:
-          path: ${{ env.BUILD_DIR_PREFIX }}/build-stuff
-          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.*') }}
-
-      - name: Run cibuildwheel
-        run: cibuildwheel
-        env:
-          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-*"
-          CIBW_ARCHS: ${{ matrix.cibw_arch }}
-          CIBW_BEFORE_ALL_LINUX: ${{ env.INSTALL_OS_PACKAGES }}
-          CIBW_ENVIRONMENT_LINUX: BUILD_DIR_PREFIX=/host${{ env.BUILD_DIR_PREFIX }}
-
-      - name: Check builded wheels
-        run: twine check wheelhouse/*
-
-      - name: Upload builded wheels
-        uses: actions/upload-artifact@v3
-        with:
-          name: wheels
-          path: wheelhouse/*.whl
-          if-no-files-found: error
-
-      - name: Fix cache permissions
-        run: sudo chmod -R 777 ${{ env.BUILD_DIR_PREFIX }}
+#  wheels_linux_cpython:
+#    strategy:
+#      fail-fast: true
+#      matrix:
+#        cibw_buildlinux: [ manylinux, musllinux ]
+#        cibw_arch: [ "aarch64", "i686", "x86_64" ]
+#    name: Wheels • ${{ matrix.cibw_buildlinux }} • ${{ matrix.cibw_arch }} • CPython
+#    runs-on: ubuntu-20.04
+#    env:
+#      BUILD_DIR_PREFIX: "/tmp/pillow_heif"
+#      KEY_HEAD: ${{ matrix.cibw_arch }}-${{ matrix.cibw_buildlinux }}
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up QEMU
+#        if: matrix.cibw_arch == 'aarch64'
+#        uses: docker/setup-qemu-action@v1
+#        with:
+#          platforms: arm64
+#
+#      - name: Install cibuildwheel & twine
+#        run: python3 -m pip install cibuildwheel twine
+#
+#      - name: manylinux preparations
+#        if: matrix.cibw_buildlinux == 'manylinux'
+#        run: echo INSTALL_OS_PACKAGES="yum makecache && yum install -y $OS_PACKAGES" >> $GITHUB_ENV
+#        env:
+#          OS_PACKAGES: "git-all libjpeg-turbo-devel lcms2-devel"
+#
+#      - name: musllinux preparations
+#        if: matrix.cibw_buildlinux == 'musllinux'
+#        run: echo INSTALL_OS_PACKAGES="apk update && apk --no-cache add $OS_PACKAGES" >> $GITHUB_ENV
+#        env:
+#          OS_PACKAGES: "sudo py3-pip python3-dev fribidi-dev harfbuzz-dev jpeg-dev lcms2-dev openjpeg-dev"
+#
+#      - name: Only minimal testing on aarch64
+#        if: matrix.cibw_arch == 'aarch64'
+#        run: echo CIBW_TEST_EXTRAS="tests-min" >> $GITHUB_ENV
+#
+#      - uses: actions/cache@v3
+#        with:
+#          path: ${{ env.BUILD_DIR_PREFIX }}/build-tools
+#          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.py') }}
+#
+#      - uses: actions/cache@v3
+#        with:
+#          path: ${{ env.BUILD_DIR_PREFIX }}/build-stuff
+#          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.*') }}
+#
+#      - name: Run cibuildwheel
+#        run: cibuildwheel
+#        env:
+#          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-*"
+#          CIBW_ARCHS: ${{ matrix.cibw_arch }}
+#          CIBW_BEFORE_ALL_LINUX: ${{ env.INSTALL_OS_PACKAGES }}
+#          CIBW_ENVIRONMENT_LINUX: BUILD_DIR_PREFIX=/host${{ env.BUILD_DIR_PREFIX }}
+#
+#      - name: Check builded wheels
+#        run: twine check wheelhouse/*
+#
+#      - name: Upload builded wheels
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: wheels
+#          path: wheelhouse/*.whl
+#          if-no-files-found: error
+#
+#      - name: Fix cache permissions
+#        run: sudo chmod -R 777 ${{ env.BUILD_DIR_PREFIX }}
 
   wheels_linux_pypy:
     strategy:
@@ -171,16 +171,9 @@ jobs:
         run: python3 -m pip install cibuildwheel twine
 
       - name: manylinux preparations
-        if: matrix.cibw_buildlinux == 'manylinux'
         run: echo INSTALL_OS_PACKAGES="yum makecache && yum install -y $OS_PACKAGES" >> $GITHUB_ENV
         env:
           OS_PACKAGES: "git-all libjpeg-turbo-devel lcms2-devel"
-
-      - name: musllinux preparations
-        if: matrix.cibw_buildlinux == 'musllinux'
-        run: echo INSTALL_OS_PACKAGES="apk update && apk --no-cache add $OS_PACKAGES" >> $GITHUB_ENV
-        env:
-          OS_PACKAGES: "sudo py3-pip python3-dev fribidi-dev harfbuzz-dev jpeg-dev lcms2-dev openjpeg-dev"
 
       - name: Only minimal testing on aarch64
         if: matrix.cibw_arch == 'aarch64'
@@ -262,43 +255,43 @@ jobs:
           name: wheels
           path: wheelhouse/*.tar.gz
 
-  draft_release:
-    needs: [sdist, wheels_linux_cpython, wheels_linux_pypy, wheels_macos, wheels_windows]
-    runs-on: ubuntu-20.04
-    name: Build and create release
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Get release info
-        id: get_release_info
-        run: |
-          RELEASE_VERSION=$(sed -n "s/^__version__.*\"\(.*\)\"$/\\1/p" ./pillow_heif/_version.py)
-          echo "::set-output name=version::v${RELEASE_VERSION}"
-          echo "::set-output name=tag::v${RELEASE_VERSION}"
-          CHANGELOG=$(grep -oPz "(?s)##\s\[$RELEASE_VERSION.+?(?=##\s\[|$)" ./CHANGELOG.md | tr -d '\0' | sed /^$/d | sed '1d')
-          CHANGELOG=$(echo "$CHANGELOG" | sed '$!N;s/^###.*\n#/#/;P;D' | sed '$!N;s/^###.*\n#/#/;P;D' | sed '${/^###/d;}')
-          if [ "$CHANGELOG" == "" ]; then
-            echo "changelog is empty!"
-            exit 1
-          fi
-          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
-          echo "$CHANGELOG" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-
-      - name: Collect sdist and wheels
-        uses: actions/download-artifact@v3
-        with:
-          name: wheels
-          path: wheelhouse
-
-      - name: Create release draft
-        uses: ncipollo/release-action@v1.10.0
-        with:
-          name: ${{ steps.get_release_info.outputs.version }}
-          tag: ${{ steps.get_release_info.outputs.tag }}
-          commit: ${{ github.ref }}
-          draft: true
-          body: ${{ env.CHANGELOG }}
-          artifacts: wheelhouse/*
-          token: ${{ secrets.GITHUB_TOKEN }}
-          artifactErrorsFailBuild: true
+#  draft_release:
+#    needs: [sdist, wheels_linux_cpython, wheels_linux_pypy, wheels_macos, wheels_windows]
+#    runs-on: ubuntu-20.04
+#    name: Build and create release
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Get release info
+#        id: get_release_info
+#        run: |
+#          RELEASE_VERSION=$(sed -n "s/^__version__.*\"\(.*\)\"$/\\1/p" ./pillow_heif/_version.py)
+#          echo "::set-output name=version::v${RELEASE_VERSION}"
+#          echo "::set-output name=tag::v${RELEASE_VERSION}"
+#          CHANGELOG=$(grep -oPz "(?s)##\s\[$RELEASE_VERSION.+?(?=##\s\[|$)" ./CHANGELOG.md | tr -d '\0' | sed /^$/d | sed '1d')
+#          CHANGELOG=$(echo "$CHANGELOG" | sed '$!N;s/^###.*\n#/#/;P;D' | sed '$!N;s/^###.*\n#/#/;P;D' | sed '${/^###/d;}')
+#          if [ "$CHANGELOG" == "" ]; then
+#            echo "changelog is empty!"
+#            exit 1
+#          fi
+#          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
+#          echo "$CHANGELOG" >> $GITHUB_ENV
+#          echo "EOF" >> $GITHUB_ENV
+#
+#      - name: Collect sdist and wheels
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: wheels
+#          path: wheelhouse
+#
+#      - name: Create release draft
+#        uses: ncipollo/release-action@v1.10.0
+#        with:
+#          name: ${{ steps.get_release_info.outputs.version }}
+#          tag: ${{ steps.get_release_info.outputs.tag }}
+#          commit: ${{ github.ref }}
+#          draft: true
+#          body: ${{ env.CHANGELOG }}
+#          artifacts: wheelhouse/*
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          artifactErrorsFailBuild: true
