dev, 0.1.10

diff --git a/.github/workflows/create-release-draft.yml b/.github/workflows/create-release-draft.yml
--- a/.github/workflows/create-release-draft.yml
+++ b/.github/workflows/create-release-draft.yml
@@ -5,35 +5,35 @@ on:
   workflow_dispatch:
 
 jobs:
-  wheels_windows:
-    name: Wheels • windows • x86_64
-    runs-on: windows-2019
-    env:
-      VCPKG_PREFIX: "C:/vcpkg/installed/x64-windows"
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install requirements and dependencies
-        run: |
-          python3 -m pip install cibuildwheel twine
-          vcpkg install aom libheif --triplet=x64-windows
-
-      - name: Run cibuildwheel
-        run: cibuildwheel
-        env:
-          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-*"
-          CIBW_ARCHS_WINDOWS: "AMD64"
-          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -v -w {dest_dir} {wheel} --add-path ${{ env.VCPKG_PREFIX }}/bin"
-
-      - name: Check built wheels
-        run: twine check wheelhouse/*
-
-      - name: Upload built wheels
-        uses: actions/upload-artifact@v3
-        with:
-          name: wheels
-          path: wheelhouse/*.whl
-          if-no-files-found: error
+#  wheels_windows:
+#    name: Wheels • windows • x86_64
+#    runs-on: windows-2019
+#    env:
+#      VCPKG_PREFIX: "C:/vcpkg/installed/x64-windows"
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Install requirements and dependencies
+#        run: |
+#          python3 -m pip install cibuildwheel twine
+#          vcpkg install aom libheif --triplet=x64-windows
+#
+#      - name: Run cibuildwheel
+#        run: cibuildwheel
+#        env:
+#          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-*"
+#          CIBW_ARCHS_WINDOWS: "AMD64"
+#          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -v -w {dest_dir} {wheel} --add-path ${{ env.VCPKG_PREFIX }}/bin"
+#
+#      - name: Check built wheels
+#        run: twine check wheelhouse/*
+#
+#      - name: Upload built wheels
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: wheels
+#          path: wheelhouse/*.whl
+#          if-no-files-found: error
 
   wheels_macos:
     name: Wheels • macosx • x86_64
@@ -109,7 +109,8 @@ jobs:
       - name: Run cibuildwheel
         run: cibuildwheel
         env:
-          CIBW_BUILD: ${{ format('pp37* pp38* cp3*-{0}_{1}', matrix.cibw_buildlinux, matrix.cibw_arch) }}
+#          CIBW_BUILD: ${{ format('pp37* pp38* cp3*-{0}_{1}', matrix.cibw_buildlinux, matrix.cibw_arch) }}
+          CIBW_BUILD: "pp37* pp38*"
           CIBW_ARCHS: ${{ matrix.cibw_arch }}
           CIBW_BEFORE_ALL_LINUX: ${{ env.INSTALL_OS_PACKAGES }}
           CIBW_ENVIRONMENT_LINUX: BUILD_DIR_PREFIX=/host${{ env.BUILD_DIR_PREFIX }}
@@ -126,89 +127,89 @@ jobs:
 
       - name: Fix cache permissions
         run: sudo chmod -R 777 ${{ env.BUILD_DIR_PREFIX }}
-
-  sdist:
-    name: Source distribution
-    runs-on: macos-11
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install requirements
-        run: |
-          python3 -m pip install --upgrade pip
-          python3 -m pip install --user check-manifest twine
-
-      - name: Run check-manifest
-        run: python3 -m check_manifest
-
-      - name: Install brew
-        run: |
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-          brew install x265 libjpeg libde265 libheif
-
-      - name: Build sdist
-        run: |
-          python3 -m pip install pytest piexif coverage pillow
-          python3 -m build --sdist --outdir wheelhouse
-
-      - name: Install and check sdist
-        run: |
-          python3 -m pip install --user wheelhouse/*.tar.gz
-          python3 -m twine check wheelhouse/*
-
-      - name: Generate coverage report
-        run: coverage run -m pytest && coverage xml
-
-      - name: Upload report to Codecov
-        uses: codecov/codecov-action@v2
-        with:
-          file: ./coverage.xml
-          fail_ci_if_error: true
-          verbose: true
-
-      - name: Upload sdist
-        uses: actions/upload-artifact@v3
-        with:
-          name: wheels
-          path: wheelhouse/*.tar.gz
-
-  draft_release:
-    needs: [sdist, wheels_linux, wheels_macos, wheels_windows]
-    runs-on: ubuntu-20.04
-    name: Build and create release
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Get release info
-        id: get_release_info
-        run: |
-          RELEASE_VERSION=$(sed -n "s/^__version__.*\"\(.*\)\"$/\\1/p" ./pillow_heif/_version.py)
-          echo "::set-output name=version::v${RELEASE_VERSION}"
-          echo "::set-output name=tag::v${RELEASE_VERSION}"
-          CHANGELOG=$(grep -oPz "(?s)##\s\[$RELEASE_VERSION.+?(?=##\s\[|$)" ./CHANGELOG.md | tr -d '\0' | sed /^$/d | sed '1d')
-          CHANGELOG=$(echo "$CHANGELOG" | sed '$!N;s/^###.*\n#/#/;P;D' | sed '$!N;s/^###.*\n#/#/;P;D' | sed '${/^###/d;}')
-          if [ "$CHANGELOG" == "" ]; then
-            echo "changelog is empty!"
-            exit 1
-          fi
-          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
-          echo "$CHANGELOG" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
-
-      - name: Collect sdist and wheels
-        uses: actions/download-artifact@v3
-        with:
-          name: wheels
-          path: wheelhouse
-
-      - name: Create release draft
-        uses: ncipollo/release-action@v1.8.8
-        with:
-          name: ${{ steps.get_release_info.outputs.version }}
-          tag: ${{ steps.get_release_info.outputs.tag }}
-          commit: ${{ github.ref }}
-          draft: true
-          body: ${{ env.CHANGELOG }}
-          artifacts: wheelhouse/*
-          token: ${{ secrets.GITHUB_TOKEN }}
-          artifactErrorsFailBuild: true
+#
+#  sdist:
+#    name: Source distribution
+#    runs-on: macos-11
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Install requirements
+#        run: |
+#          python3 -m pip install --upgrade pip
+#          python3 -m pip install --user check-manifest twine
+#
+#      - name: Run check-manifest
+#        run: python3 -m check_manifest
+#
+#      - name: Install brew
+#        run: |
+#          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+#          brew install x265 libjpeg libde265 libheif
+#
+#      - name: Build sdist
+#        run: |
+#          python3 -m pip install pytest piexif coverage pillow
+#          python3 -m build --sdist --outdir wheelhouse
+#
+#      - name: Install and check sdist
+#        run: |
+#          python3 -m pip install --user wheelhouse/*.tar.gz
+#          python3 -m twine check wheelhouse/*
+#
+#      - name: Generate coverage report
+#        run: coverage run -m pytest && coverage xml
+#
+#      - name: Upload report to Codecov
+#        uses: codecov/codecov-action@v2
+#        with:
+#          file: ./coverage.xml
+#          fail_ci_if_error: true
+#          verbose: true
+#
+#      - name: Upload sdist
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: wheels
+#          path: wheelhouse/*.tar.gz
+#
+#  draft_release:
+#    needs: [sdist, wheels_linux, wheels_macos, wheels_windows]
+#    runs-on: ubuntu-20.04
+#    name: Build and create release
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Get release info
+#        id: get_release_info
+#        run: |
+#          RELEASE_VERSION=$(sed -n "s/^__version__.*\"\(.*\)\"$/\\1/p" ./pillow_heif/_version.py)
+#          echo "::set-output name=version::v${RELEASE_VERSION}"
+#          echo "::set-output name=tag::v${RELEASE_VERSION}"
+#          CHANGELOG=$(grep -oPz "(?s)##\s\[$RELEASE_VERSION.+?(?=##\s\[|$)" ./CHANGELOG.md | tr -d '\0' | sed /^$/d | sed '1d')
+#          CHANGELOG=$(echo "$CHANGELOG" | sed '$!N;s/^###.*\n#/#/;P;D' | sed '$!N;s/^###.*\n#/#/;P;D' | sed '${/^###/d;}')
+#          if [ "$CHANGELOG" == "" ]; then
+#            echo "changelog is empty!"
+#            exit 1
+#          fi
+#          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
+#          echo "$CHANGELOG" >> $GITHUB_ENV
+#          echo "EOF" >> $GITHUB_ENV
+#
+#      - name: Collect sdist and wheels
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: wheels
+#          path: wheelhouse
+#
+#      - name: Create release draft
+#        uses: ncipollo/release-action@v1.8.8
+#        with:
+#          name: ${{ steps.get_release_info.outputs.version }}
+#          tag: ${{ steps.get_release_info.outputs.tag }}
+#          commit: ${{ github.ref }}
+#          draft: true
+#          body: ${{ env.CHANGELOG }}
+#          artifacts: wheelhouse/*
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          artifactErrorsFailBuild: true
